version: '3.8'

services:
  binance_proxy_nightshift2k:
    image: nightshift2k/binance-proxy:latest
    container_name: binance_proxy_nightshift2k
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8091:8091"

  # BASE CONTAINER
  freqtrade:
    environment:
      SLEEP: "0"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
      - "8100:8100"
      - "8101:8101"
      - "8102:8102"
      - "8103:8103"
      - "8104:8104"
      - "8105:8105"
      - "8106:8106"
      - "8107:8107"
      - "8108:8108"
      - "8109:8109"
      - "8110:8110"
      - "8111:8111"
      - "8112:8112"
      - "8113:8113"
      - "8114:8114"
      - "8115:8115"
      - "8116:8116"
      - "8117:8117"
      - "8118:8118"
      - "8119:8119"
      - "8120:8120"
      - "8121:8121"
      - "8122:8122"
      - "8123:8123"
      - "8124:8124"
      - "8125:8125"
      - "8126:8126"
      - "8127:8127"
      - "8128:8128"
      - "8129:8129"
      - "8130:8130"
      - "8131:8131"
      - "8132:8132"
      - "8133:8133"
      - "8134:8134"
      - "8135:8135"
      - "8136:8136"
      - "8137:8137"
      - "8138:8138"
      - "8139:8139"
      - "8140:8140"
    links:
      - "binance_proxy_nightshift2k"
    depends_on:
      - "binance_proxy_nightshift2k"
    command: >
      freqtrade webserver
      --config /freqtrade/user_data/config/default.json      
      --config /freqtrade/user_data/config/exchange/binance.json      
